### ISSUE TITLE
ODataClient constructor should support Uri object

### ISSUE THREAD

**Issue by vojtechvit** [object/Simple.OData.Client#103]
I tried to create ODataClient (V4) this way:

``` c#
var client = new ODataClient(new Uri("http://localhost:15407/v1"));
``` 
and I was surprised by a compilation error because ODataClient does not accept Uri class in the constructor. I think this should be fixed since storing Uris in strings is actually considered a bad practice... :-) Maybe try to turn on and run Code Analysis in Simple OData Client projects - it would complain about this kind of issues at build time.

See https://msdn.microsoft.com/en-us/library/ms182360.aspx

**Comment by object** [comment]
Good point. I will add an overload in 4.5.

**Comment by object** [comment]
Resolved in 4.5 (available via MyGet feed until the release).
